test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    # 入力フォーム
    path('welcome/', views.welcome, name='welcome'),
    path('welcome_widget/', views.welcome_widget, name='welcome_widget'),
    path('confirm/', views.confirm, name='confirm'),
    path('thankyou/', views.sent, name='sent'),
    # 情報閲覧管理者画面
    path('history/<int:page>/', views.history, name='history'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('confirm_contact/<int:pk>/', views.confirm_contact, name='confirm_contact'),
    path('sent_contact/<int:pk>/', views.sent_contact, name='sent_contact'),

    path('update_visitors/<int:pk>/', views.VisitorsUpdate.as_view(), name='update_visitors'),
    path('update_contact/<int:pk>/<int:id>/', views.ContactUpdate.as_view(), name='update_contact'),
    # path('update_contact_all/<int:pk>/', views.VisitorsContactUpdateFormSetView.as_view(), name='update_contact_all'),
    path('update_allpost/<int:pk>/', views.update_allpost, name='update_allpost'),

    path('delete_contact/<int:pk>/', views.ContactDelete.as_view(), name='delete_contact'),
    path('delete_contact_all/<int:pk>/', views.VisitorsDelete.as_view(), name='delete_contact_all'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/views.py
from turtle import position
from django.shortcuts import get_object_or_404, render
from .models import *
from django.urls import reverse_lazy
from .forms import ContactForm, MemberForm, VisitorsForm
from django.views.generic import UpdateView
from django import forms
from django.shortcuts import redirect
from django.contrib import messages

# Create your views here.

def index(request):
    context = {
        'msg': 'Hello, world!!',
    }
    return render(request, 'test_app/index.html', context)


def welcome(request):
    context = {
        'msg': 'ようこそ！！'
    }
    return render(request, 'test_app/entry_form/welcome.html', context)


def confirm(request):
    if request.method == 'POST':
        context = {
            'date': request.POST.get('date'),
            'time': request.POST.get('time'),
            'company_name': request.POST.get('company_name'),
            'visitor_name': request.POST.get('visitor_name'),
            'temperature': request.POST.get('temperature'),
            'accompany1_name': request.POST.get('accompany1_name'),
            'accompany1_temp': request.POST.get('accompany1_temp'),
            'accompany2_name': request.POST.get('accompany2_name'),
            'accompany2_temp': request.POST.get('accompany2_temp'),
            'accompany3_name': request.POST.get('accompany3_name'),
            'accompany3_temp': request.POST.get('accompany3_temp'),
            'position': request.POST.get('position'),
            'interviewer': request.POST.get('interviewer'),
            'content': request.POST.get('content'),
        }
    return render(request, 'test_app/confirm.html', context)


def sent(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        time = request.POST.get('time')
        company_name = request.POST.get('company_name')
        visitor_name = request.POST.get('visitor_name')
        temperature = request.POST.get('temperature')
        accompany1_name = request.POST.get('accompany1_name')
        accompany1_temp = request.POST.get('accompany1_temp')
        accompany2_name = request.POST.get('accompany2_name')
        accompany2_temp = request.POST.get('accompany2_temp')
        accompany3_name = request.POST.get('accompany3_name')
        accompany3_temp = request.POST.get('accompany3_temp')
        position = request.POST.get('position')
        interviewer = request.POST.get('interviewer')
        content = request.POST.get('content')

        Visitors.objects.create(date=date, time=time, company_name=company_name, visitor_name=visitor_name,
        temperature=temperature, accompany1_name=accompany1_name, accompany1_temp=accompany1_temp, accompany2_name=accompany2_name,
        accompany2_temp=accompany2_temp, accompany3_name=accompany3_name, accompany3_temp=accompany3_temp, position=position,
        interviewer=interviewer, content=content)
    return render(request, 'test_app/lazy/thankyou.html')


def history(request):
    visitors = Visitors.objects.all()
    context = {
        'visitors': visitors,
    }
    visitor_type = Visitors.objects.all().values_list('visitor_name', flat=True).order_by('visitor_name').distinct()
    print(visitor_type)
    visitor_type1 = visitor_type.get(visitor_name='小川')
    print(visitor_type1)
    return render(request, 'test_app/history.html', context)


def detail(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    print(visitor.is_contacted)
    if visitor.is_contacted:
        # contact = visitor.contact_set.all()
        contact = Contact.objects.filter(contact__pk=pk)[0]
        context = {
            'visitor': visitor,
            'contact': contact,
        }
        print(contact)
    else:
        form = MemberForm()
        context = {
            'visitor': visitor,
            'form': form,
        }
    
    return render(request, 'test_app/detail.html', context)


def confirm_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    
    form = MemberForm(request.POST)
    if form.is_valid():
        interviewer = form.cleaned_data['member']
    if request.method == 'POST':
        context = {
            'visitor': visitor,
            'interviewer': interviewer,
            'time': request.POST.get('time'),
            'contents': request.POST.get('contents'),
        }
    return render(request, 'test_app/confirm_contact.html', context)



def sent_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    visitor.save()
    if request.method == 'POST':
        contact = visitor
        interviewer_post_name = request.POST.get('interviewer')
        print(interviewer_post_name)
        target = '/'
        idx = interviewer_post_name.find(target)
        interviewer_name = interviewer_post_name[idx+2:]
        print(interviewer_name)
        if interviewer_post_name == "None":
            interviewer = None
        else:
            interviewer = Member.objects.get(name=interviewer_name)
            visitor.is_contacted = True
        time = request.POST.get('time')
        if time == "":
            time = '00:00'
        contents = request.POST.get('contents')
        try:
            contact = Contact.objects.get(contact_id=pk)
            contact.interviewer = interviewer
            contact.time = time
            contact.contents = contents
        except:
            Contact.objects.create(contact=contact, interviewer=interviewer, time=time, contents=contents)

    return render(request, 'test_app/lazy/thankyou_contact.html')


"""
UpdateとDelete
"""
class VisitorsUpdate(UpdateView):
    template_name = 'test_app/update_visitors.html'
    form_class = VisitorsForm
    model = Visitors
    
    def get_success_url(self):
        messages.info(self.request, f'訪問者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})


class ContactUpdate(UpdateView):
    template_name = 'test_app/update_contact.html'
    form_class = ContactForm
    model = Contact

    def get_success_url(self, **kwargs):
        messages.info(self.request, f'担当者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['id']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
        return context


# class ContactAllUpdate(UpdateView):
#     template_name = 'test_app/update_contact.html'
#     form_class = VisitorsForm
#     model = Visitors

#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})

    # def get_context_data(self):
    #     context = super().get_context_data()
    #     context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
    #     return context


# from extra_views import InlineFormSetView, UpdateWithInlinesView


# class ContactInlineFormSet(InlineFormSetView):
#     model = Contact
#     fields = ("interviewer", "time", "contents")
#     can_delete = True

# class VisitorsContactUpdateFormSetView(UpdateWithInlinesView):
#     model = Visitors
#     fields = ('date', 'time', 'company_name', 'visitor_name', 'temperature',
#                 'accompany1_name', 'accompany1_temp', 'accompany2_name', 'accompany2_temp',
#                 'accompany3_name', 'accompany3_temp', 'position', 'interviewer', 'content',
#                 'is_contacted')
#     inlines = [ContactInlineFormSet, ]
#     template_name = "test_app/update_contact.html"
    
#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})





def update_allpost(request, pk):
    visitors = get_object_or_404(Visitors, pk=pk)
    form = VisitorsForm(request.POST or None, instance=visitors)
    ContactFormset = forms.inlineformset_factory(
            Visitors, Contact, fields=('interviewer', 'time', 'contents'),
            can_delete=False,
            widgets={
                'interviewer': forms.Select(attrs={'class': 'form-control'}),
                'time': forms.TimeInput(attrs={'class': 'form-control'}),
                'contents': forms.Textarea(attrs={'class': 'form-control'}),
            }
        )
    formset = ContactFormset(request.POST or None, instance=visitors)  # 今回はファイルなのでrequest.FILESが必要
    if request.method == 'POST' and form.is_valid():
        form.save()
        print('POSTメソッド')
        print(formset.errors)
        print()
        if formset.is_valid():
            print('formset.save()')
            formset.save()
            return redirect('test_app:detail', pk=pk)
    else:
        print('POSTメソッドだけども・・・')

    # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
    context = {
        'form': form,
        'formset': formset,
    }
    print(formset)
    print('GETメソッド')
    return render(request, 'test_app/update_allpost.html', context)

test_app/views/update_delete_views.py
from turtle import position
from django.shortcuts import get_object_or_404, render
from ..models import *
from django.urls import reverse_lazy
from ..forms import ContactForm, MemberForm, VisitorsForm
from django.views.generic import UpdateView, DeleteView
from django import forms
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse

# Create your views here.


"""
UpdateとDelete
"""
class VisitorsUpdate(UpdateView):
    template_name = 'test_app/update_visitors.html'
    form_class = VisitorsForm
    model = Visitors
    
    def get_success_url(self):
        messages.info(self.request, f'訪問者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})


class ContactUpdate(UpdateView):
    template_name = 'test_app/update_contact.html'
    form_class = ContactForm
    model = Contact

    def get_success_url(self, **kwargs):
        messages.info(self.request, f'担当者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['id']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
        return context


# class ContactAllUpdate(UpdateView):
#     template_name = 'test_app/update_contact.html'
#     form_class = VisitorsForm
#     model = Visitors

#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})

    # def get_context_data(self):
    #     context = super().get_context_data()
    #     context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
    #     return context


# from extra_views import InlineFormSetView, UpdateWithInlinesView


# class ContactInlineFormSet(InlineFormSetView):
#     model = Contact
#     fields = ("interviewer", "time", "contents")
#     can_delete = True

# class VisitorsContactUpdateFormSetView(UpdateWithInlinesView):
#     model = Visitors
#     fields = ('date', 'time', 'company_name', 'visitor_name', 'temperature',
#                 'accompany1_name', 'accompany1_temp', 'accompany2_name', 'accompany2_temp',
#                 'accompany3_name', 'accompany3_temp', 'position', 'interviewer', 'content',
#                 'is_contacted')
#     inlines = [ContactInlineFormSet, ]
#     template_name = "test_app/update_contact.html"
    
#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})





def update_allpost(request, pk):
    visitors = get_object_or_404(Visitors, pk=pk)
    form = VisitorsForm(request.POST or None, instance=visitors)
    ContactFormset = forms.inlineformset_factory(
            Visitors, Contact, fields=('interviewer', 'time', 'contents'),
            can_delete=False,
            widgets={
                'interviewer': forms.Select(attrs={'class': 'form-control'}),
                'time': forms.TimeInput(attrs={'class': 'form-control'}),
                'contents': forms.Textarea(attrs={'class': 'form-control'}),
            }
        )
    formset = ContactFormset(request.POST or None, instance=visitors)  # 今回はファイルなのでrequest.FILESが必要
    if request.method == 'POST' and form.is_valid():
        form.save()
        print('POSTメソッド')
        print(formset.errors)
        print()
        if formset.is_valid():
            print('formset.save()')
            formset.save()
            return redirect('test_app:detail', pk=pk)
    else:
        print('POSTメソッドだけども・・・')

    # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
    context = {
        'form': form,
        'formset': formset,
    }
    print(formset)
    print('GETメソッド')
    return render(request, 'test_app/update_allpost.html', context)


"""
Delete機能
"""
class ContactDelete(DeleteView):
        
    model = Contact
    template_name = 'test_app/delete_contact.html'
    success_url = reverse_lazy('test_app:history')

    def get_success_url(self):
        return reverse('test_app:history', kwargs={'page': '1'})

    def get(self, request, *args, **kwargs):
        visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        contact = Contact.objects.get(id=self.kwargs['pk'])
        print('DeleteView/getメソッド')
        print(contact)
        print(contact.id)
        print(visitor)
        print(visitor.id)
        print(visitor.is_contacted)
        contact = Contact.objects.get(pk=self.kwargs['pk'])
        context = {
            'contact': contact,
        }
        return render(request, 'test_app/delete_contact.html', context)

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        # visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        # print(visitor)
        # print(visitor.id)
        # print(visitor.is_contacted)
        # visitor.is_contacted = False
        # print(visitor.is_contacted)
        # visitor.save()
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

    def post(self, request, *args, **kwargs):
        visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        print(visitor)
        print(visitor.id)
        print(visitor.is_contacted)
        visitor.is_contacted = False
        print(visitor.is_contacted)
        visitor.save()
        return self.delete(request)


class VisitorsDelete(DeleteView):

    model = Visitors
    template_name = 'test_app/delete_contact_all.html'
    success_url = reverse_lazy('test_app:history')

    def get_success_url(self):
        return reverse('test_app:history', kwargs={'page': '1'})
    
    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        # visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        # print(visitor)
        # print(visitor.id)
        # print(visitor.is_contacted)
        # visitor.is_contacted = False
        # print(visitor.is_contacted)
        # visitor.save()
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

    def form_valid(self, form):
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return super().form_valid(form)

test_app/templates/test_app/block.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}  
{% block title%}{% endblock %}

    {% block header %}
    {% endblock %}
{% block content %}
{% endblock %}

test_app/templates/test_app/history copy.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  
  <title>INDEX</title>
</head>
<body>
  <div class="container-fluid-list">
    <div class="row">
  
    <table class="table table-bordered border-success table-hover">
        <thead class="table-success">
          <tr>
            <th scope="col">id</th>
            <th scope="col">日付</th>
            <th scope="col">会社名</th>
            <th scope="col" width="8%">訪問者氏名</th>
            <th scope="col" width="20%">ご用件</th>
            <th scope="col" width="10%">対応担当者</th>
            <th scope="col" width="16%">内容</th>
            <th scope="col" width="3%"></th>
            <th scope="col" width="6%">操作</td>
            <th scope="col" width="6%">操作</td>
            <th scope="col" width="6%">操作</td>
            <th scope="col" width="6%">操作</td>
            <th scope="col" width="6%">操作</td>
          </tr>
        </thead>
        {% for visitor in visitors %}
        <tbody>
          
          <tr data-href="{% url 'test_app:detail' visitor.pk %}">
            <th scope="row">{{ visitor.id }}</th>
            <td>{{ visitor.date }}</td>
            <td>{{ visitor.company_name }}</td>
            <td>{{ visitor.visitor_name }}</td>
            <td>{{ visitor.content | linebreaksbr | truncatechars:30 }}</td>
            {% if visitor.is_contacted %}
            <td>{{ visitor.contact.interviewer }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if visitor.is_contacted %}
            <td>{{ visitor.contact.contents | linebreaksbr | truncatechars:30 }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if visitor.is_contacted %}
            <td>✅</td>
            {% else %}
            <td>&#10060;</td>
            {% endif %}
            <td>
              <button class="favorite styled" type="button" onclick="location.href='{% url 'test_app:update_visitors' visitor.pk %}'">編集1</button>
            </td>
            {% if visitor.contact.pk %}
            <td>
              <button class="favorite styled" type="button" onclick="location.href='{% url 'test_app:update_contact' visitor.contact.pk visitor.pk %}'">編集2</button>
            </td>
            {% else %}
            <td></td>
            {% endif %}
            {% if visitor.contact.pk %}
            <td>
              <button class="favorite styled" type="button" onclick="location.href='{% url 'test_app:update_allpost' visitor.pk %}'">編集3</button>
            </td>
            {% else %}
            <td></td>
            {% endif %}
            <td>
              <button class="favorite styled" type="button" onclick="location.href='#'">削除1</button>
            </td>
            <td>
              <button class="favorite styled" type="button" onclick="location.href='#'">削除2</button>
            </td>
          </tr>
        </tbody>
        {% endfor %}
      </table>
    </div>
  </div>
  <script>
  jQuery(function($) {
 
    //data-hrefの属性を持つtrを選択しclassにclickableを付加
    $('tr[data-href]').addClass('clickable')
     
      //クリックイベント
      .click(function(e) {
     
        //e.targetはクリックした要素自体、それがa要素以外であれば
        if(!$(e.target).is('a' && 'button')){
         
          //その要素の先祖要素で一番近いtrの
          //data-href属性の値に書かれているURLに遷移する
          window.location = $(e.target).closest('tr').data('href');}
    });
  });
</script>
</body>
</html>

test_app/templates/test_app/history.html
{% extends 'base.html' %}
{% block head %}
{% endblock %}  
{% block title%}対応状況一覧{% endblock %}

    {% block header %}
    <div class="row">
    <div class="col-10">
    <h1>コンタクト一覧</h1>
    </div>
    <div class="col-2">
    <form class="form-inline my-2 my-lg-0 ml-auto" method="post">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="search_form">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    </div>
    </div>
    {% endblock %}
{% block content %}
  <div class="container-fluid-list">
    <div class="row">
       <!-- メッセージ表示 -->
       {% if messages %}
       {% for message in messages %}
       <div class="alert alert-success" role="alert">
          {{ message }}
       </div>
       {% endfor %}
       {% endif %}
  
    <table class="table table-bordered border-success table-hover">
        <thead class="table-success">
          <tr>
            <th scope="col">id</th>
            <th scope="col">日付</th>
            <th scope="col">会社名</th>
            <th scope="col" width="8%">訪問者氏名</th>
            <th scope="col" width="20%">ご用件</th>
            <th scope="col" width="3%">label</th>
            <th scope="col" width="10%">対応担当者</th>
            <th scope="col" width="16%">内容</th>
            <th scope="col" width="5%">操作</td>
            <th scope="col" width="6%">操作</td>
            {% comment %} <th scope="col" width="6%">操作</td> {% endcomment %}
          </tr>
        </thead>
        {% for visitor in visitors %}
        <tbody>
          
          <tr data-href="{% url 'test_app:detail' visitor.pk %}">
            <th scope="row">{{ visitor.id }}</th>
            <td>{{ visitor.date }}</td>
            <td>{{ visitor.company_name }}</td>
            <td>{{ visitor.visitor_name }}</td>
            <td>{{ visitor.content | linebreaksbr | truncatechars:30 }}</td>
            {% if visitor.is_contacted %}
            <td>✅</td>
            {% else %}
            <td>&#10060;</td>
            {% endif %}
            {% if visitor.is_contacted %}
            <td>{{ visitor.contact.interviewer }}</td>
            {% else %}
            <td></td>
            {% endif %}
            {% if visitor.is_contacted %}
            <td>{{ visitor.contact.contents | linebreaksbr | truncatechars:30 }}</td>
            {% else %}
            <td></td>
            {% endif %}
            <td>
              {% if not visitor.contact.pk %}
              <button class="btn btn-success" type="button" onclick="location.href='{% url 'test_app:update_visitors' visitor.pk %}'">編集　</button>
              {% else %}
              <div class="dropdown" id="target">
                <button class="btn btn-success dropdown-toggle"
                        type="button" id="dropdownMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                  編集
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  {% if visitor.contact.pk %}
                  <a class="dropdown-item" href="{% url 'test_app:update_contact' visitor.contact.pk visitor.pk %}">コンタクト編集</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'test_app:update_visitors' visitor.pk %}">来訪情報編集</a>
                  {% if visitor.contact.pk %}
                  <a class="dropdown-item" href="{% url 'test_app:update_allpost' visitor.pk %}">一括編集</a>
                  {% endif %}
                </div>
              </div>
              {% endif %}
            </td>
            <td>
              {% if not visitor.contact.pk %}
              <button class="btn btn-success" type="button" onclick="location.href='{% url 'test_app:delete_contact_all' visitor.pk %}'">削除　</button>
              {% else %}
              <div class="dropdown" id="target">
                <button class="btn btn-success dropdown-toggle"
                        type="button" id="dropdownMenu1" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                  削除
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  {% if visitor.contact.pk %}
                  <a class="dropdown-item" href="{% url 'test_app:delete_contact' visitor.contact.pk %}">コンタクト削除</a>
                  {% endif %}
                  <a class="dropdown-item" href="{% url 'test_app:delete_contact_all' visitor.pk %}">一括削除</a>
                </div>
              </div>
              {% endif %}
            </td>
            {% comment %} <td>
              <button class="favorite styled" type="button" onclick="location.href='#'">削除2</button>
            </td> {% endcomment %}
          </tr>
        </tbody>
        {% endfor %}
      </table>
      
      <div>
        <br>
      </div>

      <!-- Pagination -->
      <nav>
        <ul class="pagination justify-content-center">
            <li class="page-item {% if not visitors.has_previous %} disabled {% endif %}">
                <a class="page-link" href="{% if visitors.has_previous %} {% url 'test_app:history' visitors.previous_page_number %}{% endif %} ">Previous</a>
            </li>

            {% if visitors.number|add:'-1' > 1 %}
                <li class="page-item disabled"><a class="page-link">&hellip;</a></li>
            {% endif %}

            {% for i in visitors.paginator.page_range %}
                {% if visitors.number == i %}
                    <li class="active page-item disabled"><a class="page-link" href="#">{{ i }}</a></li>
                {% elif i > visitors.number|add:'-2' and i < visitors.number|add:'2' %}
                    <li class="page-item"><a class="page-link" href="{% url 'test_app:history' i %}">{{ i }}</a></li>
                {% endif %}
            {% endfor %}

            {% if visitors.paginator.num_pages > visitors.number|add:'1' %}
                <li class="page-item disabled"><a class="page-link" href="#">&hellip;</a></li>
            {% endif %}

            <li class="page-item {% if not visitors.has_next %} disabled {% endif %}">
                <a class="page-link" href="{% if visitors.has_next %} {% url 'test_app:history' visitors.next_page_number %} {% endif %}">Next</a>
            </li>
        </ul>
      </nav>  
      <!-- END Pagination -->



    </div>
  </div>
  <script>
  jQuery(function($) {
 
    //data-hrefの属性を持つtrを選択しclassにclickableを付加
    $('tr[data-href]').addClass('clickable')
     
      //クリックイベント
      .click(function(e) {
        //e.targetはクリックした要素自体、それがa要素以外であれば
        if(!$(e.target).is('a' && 'button')){
         
          //その要素の先祖要素で一番近いtrの
          //data-href属性の値に書かれているURLに遷移する
          window.location = $(e.target).closest('tr').data('href');}
    });
  });
</script>

{% endblock %}

test_app/templates/test_app/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>INDEX</title>
  </head>
  <body>
    <h1>{{msg}}</h1>
    <input type="hidden" name="contact-TOTAL_FORMS" value="1" id="id_contact-TOTAL_FORMS">
    <input type="hidden" name="contact-INITIAL_FORMS" value="1" id="id_contact-INITIAL_FORMS">
    <input type="hidden" name="contact-MIN_NUM_FORMS" value="0" id="id_contact-MIN_NUM_FORMS">
    <input type="hidden" name="contact-MAX_NUM_FORMS" value="1" id="id_contact-MAX_NUM_FORMS">
<tr>
<td colspan="2">
<ul class="errorlist nonfield">
<li>(Hidden field contact) コンタクト履歴 with this 来訪者履歴 already exists.</li>
<li>(Hidden field id) This field is required.</li>
</ul>
</td>
</tr>
  </body>
</html>