test_app/urls.py
from django.urls import path
from . import views

app_name = 'test_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    # 入力フォーム
    path('welcome/', views.welcome, name='welcome'),
    path('welcome_widget/', views.welcome_widget, name='welcome_widget'),
    path('confirm/', views.confirm, name='confirm'),
    path('thankyou/', views.sent, name='sent'),
    # 情報閲覧管理者画面
    path('history/<int:page>/', views.history, name='history'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('confirm_contact/<int:pk>/', views.confirm_contact, name='confirm_contact'),
    path('sent_contact/<int:pk>/', views.sent_contact, name='sent_contact'),

    path('update_visitors/<int:pk>/', views.VisitorsUpdate.as_view(), name='update_visitors'),
    path('update_contact/<int:pk>/<int:id>/', views.ContactUpdate.as_view(), name='update_contact'),
    # path('update_contact_all/<int:pk>/', views.VisitorsContactUpdateFormSetView.as_view(), name='update_contact_all'),
    path('update_allpost/<int:pk>/', views.update_allpost, name='update_allpost'),

    path('delete_contact/<int:pk>/', views.ContactDelete.as_view(), name='delete_contact'),
    path('delete_contact_all/<int:pk>/', views.VisitorsDelete.as_view(), name='delete_contact_all'),
]

test_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('test_app.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_app/views.py
from turtle import position
from django.shortcuts import get_object_or_404, render
from .models import *
from django.urls import reverse_lazy
from .forms import ContactForm, MemberForm, VisitorsForm
from django.views.generic import UpdateView
from django import forms
from django.shortcuts import redirect
from django.contrib import messages

# Create your views here.

def index(request):
    context = {
        'msg': 'Hello, world!!',
    }
    return render(request, 'test_app/index.html', context)


def welcome(request):
    context = {
        'msg': 'ようこそ！！'
    }
    return render(request, 'test_app/entry_form/welcome.html', context)


def confirm(request):
    if request.method == 'POST':
        context = {
            'date': request.POST.get('date'),
            'time': request.POST.get('time'),
            'company_name': request.POST.get('company_name'),
            'visitor_name': request.POST.get('visitor_name'),
            'temperature': request.POST.get('temperature'),
            'accompany1_name': request.POST.get('accompany1_name'),
            'accompany1_temp': request.POST.get('accompany1_temp'),
            'accompany2_name': request.POST.get('accompany2_name'),
            'accompany2_temp': request.POST.get('accompany2_temp'),
            'accompany3_name': request.POST.get('accompany3_name'),
            'accompany3_temp': request.POST.get('accompany3_temp'),
            'position': request.POST.get('position'),
            'interviewer': request.POST.get('interviewer'),
            'content': request.POST.get('content'),
        }
    return render(request, 'test_app/confirm.html', context)


def sent(request):
    if request.method == 'POST':
        date = request.POST.get('date')
        time = request.POST.get('time')
        company_name = request.POST.get('company_name')
        visitor_name = request.POST.get('visitor_name')
        temperature = request.POST.get('temperature')
        accompany1_name = request.POST.get('accompany1_name')
        accompany1_temp = request.POST.get('accompany1_temp')
        accompany2_name = request.POST.get('accompany2_name')
        accompany2_temp = request.POST.get('accompany2_temp')
        accompany3_name = request.POST.get('accompany3_name')
        accompany3_temp = request.POST.get('accompany3_temp')
        position = request.POST.get('position')
        interviewer = request.POST.get('interviewer')
        content = request.POST.get('content')

        Visitors.objects.create(date=date, time=time, company_name=company_name, visitor_name=visitor_name,
        temperature=temperature, accompany1_name=accompany1_name, accompany1_temp=accompany1_temp, accompany2_name=accompany2_name,
        accompany2_temp=accompany2_temp, accompany3_name=accompany3_name, accompany3_temp=accompany3_temp, position=position,
        interviewer=interviewer, content=content)
    return render(request, 'test_app/lazy/thankyou.html')


def history(request):
    visitors = Visitors.objects.all()
    context = {
        'visitors': visitors,
    }
    visitor_type = Visitors.objects.all().values_list('visitor_name', flat=True).order_by('visitor_name').distinct()
    print(visitor_type)
    visitor_type1 = visitor_type.get(visitor_name='小川')
    print(visitor_type1)
    return render(request, 'test_app/history.html', context)


def detail(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    print(visitor.is_contacted)
    if visitor.is_contacted:
        # contact = visitor.contact_set.all()
        contact = Contact.objects.filter(contact__pk=pk)[0]
        context = {
            'visitor': visitor,
            'contact': contact,
        }
        print(contact)
    else:
        form = MemberForm()
        context = {
            'visitor': visitor,
            'form': form,
        }
    
    return render(request, 'test_app/detail.html', context)


def confirm_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    
    form = MemberForm(request.POST)
    if form.is_valid():
        interviewer = form.cleaned_data['member']
    if request.method == 'POST':
        context = {
            'visitor': visitor,
            'interviewer': interviewer,
            'time': request.POST.get('time'),
            'contents': request.POST.get('contents'),
        }
    return render(request, 'test_app/confirm_contact.html', context)



def sent_contact(request, pk):
    visitor = Visitors.objects.get(pk=pk)
    visitor.save()
    if request.method == 'POST':
        contact = visitor
        interviewer_post_name = request.POST.get('interviewer')
        print(interviewer_post_name)
        target = '/'
        idx = interviewer_post_name.find(target)
        interviewer_name = interviewer_post_name[idx+2:]
        print(interviewer_name)
        if interviewer_post_name == "None":
            interviewer = None
        else:
            interviewer = Member.objects.get(name=interviewer_name)
            visitor.is_contacted = True
        time = request.POST.get('time')
        if time == "":
            time = '00:00'
        contents = request.POST.get('contents')
        try:
            contact = Contact.objects.get(contact_id=pk)
            contact.interviewer = interviewer
            contact.time = time
            contact.contents = contents
        except:
            Contact.objects.create(contact=contact, interviewer=interviewer, time=time, contents=contents)

    return render(request, 'test_app/lazy/thankyou_contact.html')


"""
UpdateとDelete
"""
class VisitorsUpdate(UpdateView):
    template_name = 'test_app/update_visitors.html'
    form_class = VisitorsForm
    model = Visitors
    
    def get_success_url(self):
        messages.info(self.request, f'訪問者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})


class ContactUpdate(UpdateView):
    template_name = 'test_app/update_contact.html'
    form_class = ContactForm
    model = Contact

    def get_success_url(self, **kwargs):
        messages.info(self.request, f'担当者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['id']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
        return context


# class ContactAllUpdate(UpdateView):
#     template_name = 'test_app/update_contact.html'
#     form_class = VisitorsForm
#     model = Visitors

#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})

    # def get_context_data(self):
    #     context = super().get_context_data()
    #     context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
    #     return context


# from extra_views import InlineFormSetView, UpdateWithInlinesView


# class ContactInlineFormSet(InlineFormSetView):
#     model = Contact
#     fields = ("interviewer", "time", "contents")
#     can_delete = True

# class VisitorsContactUpdateFormSetView(UpdateWithInlinesView):
#     model = Visitors
#     fields = ('date', 'time', 'company_name', 'visitor_name', 'temperature',
#                 'accompany1_name', 'accompany1_temp', 'accompany2_name', 'accompany2_temp',
#                 'accompany3_name', 'accompany3_temp', 'position', 'interviewer', 'content',
#                 'is_contacted')
#     inlines = [ContactInlineFormSet, ]
#     template_name = "test_app/update_contact.html"
    
#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})





def update_allpost(request, pk):
    visitors = get_object_or_404(Visitors, pk=pk)
    form = VisitorsForm(request.POST or None, instance=visitors)
    ContactFormset = forms.inlineformset_factory(
            Visitors, Contact, fields=('interviewer', 'time', 'contents'),
            can_delete=False,
            widgets={
                'interviewer': forms.Select(attrs={'class': 'form-control'}),
                'time': forms.TimeInput(attrs={'class': 'form-control'}),
                'contents': forms.Textarea(attrs={'class': 'form-control'}),
            }
        )
    formset = ContactFormset(request.POST or None, instance=visitors)  # 今回はファイルなのでrequest.FILESが必要
    if request.method == 'POST' and form.is_valid():
        form.save()
        print('POSTメソッド')
        print(formset.errors)
        print()
        if formset.is_valid():
            print('formset.save()')
            formset.save()
            return redirect('test_app:detail', pk=pk)
    else:
        print('POSTメソッドだけども・・・')

    # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
    context = {
        'form': form,
        'formset': formset,
    }
    print(formset)
    print('GETメソッド')
    return render(request, 'test_app/update_allpost.html', context)

test_app/views/update_delete_views.py
from turtle import position
from django.shortcuts import get_object_or_404, render
from ..models import *
from django.urls import reverse_lazy
from ..forms import ContactForm, MemberForm, VisitorsForm
from django.views.generic import UpdateView, DeleteView
from django import forms
from django.shortcuts import redirect
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse

# Create your views here.


"""
UpdateとDelete
"""
class VisitorsUpdate(UpdateView):
    template_name = 'test_app/update_visitors.html'
    form_class = VisitorsForm
    model = Visitors
    
    def get_success_url(self):
        messages.info(self.request, f'訪問者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})


class ContactUpdate(UpdateView):
    template_name = 'test_app/update_contact.html'
    form_class = ContactForm
    model = Contact

    def get_success_url(self, **kwargs):
        messages.info(self.request, f'担当者情報を更新しました！')
        return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['id']})

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
        return context


# class ContactAllUpdate(UpdateView):
#     template_name = 'test_app/update_contact.html'
#     form_class = VisitorsForm
#     model = Visitors

#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})

    # def get_context_data(self):
    #     context = super().get_context_data()
    #     context['visitor'] = Visitors.objects.get(pk=self.kwargs['id'])
    #     return context


# from extra_views import InlineFormSetView, UpdateWithInlinesView


# class ContactInlineFormSet(InlineFormSetView):
#     model = Contact
#     fields = ("interviewer", "time", "contents")
#     can_delete = True

# class VisitorsContactUpdateFormSetView(UpdateWithInlinesView):
#     model = Visitors
#     fields = ('date', 'time', 'company_name', 'visitor_name', 'temperature',
#                 'accompany1_name', 'accompany1_temp', 'accompany2_name', 'accompany2_temp',
#                 'accompany3_name', 'accompany3_temp', 'position', 'interviewer', 'content',
#                 'is_contacted')
#     inlines = [ContactInlineFormSet, ]
#     template_name = "test_app/update_contact.html"
    
#     def get_success_url(self):
#         return reverse_lazy('test_app:detail', kwargs={'pk': self.kwargs['pk']})





def update_allpost(request, pk):
    visitors = get_object_or_404(Visitors, pk=pk)
    form = VisitorsForm(request.POST or None, instance=visitors)
    ContactFormset = forms.inlineformset_factory(
            Visitors, Contact, fields=('interviewer', 'time', 'contents'),
            can_delete=False,
            widgets={
                'interviewer': forms.Select(attrs={'class': 'form-control'}),
                'time': forms.TimeInput(attrs={'class': 'form-control'}),
                'contents': forms.Textarea(attrs={'class': 'form-control'}),
            }
        )
    formset = ContactFormset(request.POST or None, instance=visitors)  # 今回はファイルなのでrequest.FILESが必要
    if request.method == 'POST' and form.is_valid():
        form.save()
        print('POSTメソッド')
        print(formset.errors)
        print()
        if formset.is_valid():
            print('formset.save()')
            formset.save()
            return redirect('test_app:detail', pk=pk)
    else:
        print('POSTメソッドだけども・・・')

    # エラーメッセージつきのformsetをテンプレートへ渡すため、contextに格納
    context = {
        'form': form,
        'formset': formset,
    }
    print(formset)
    print('GETメソッド')
    return render(request, 'test_app/update_allpost.html', context)


"""
Delete機能
"""
class ContactDelete(DeleteView):
        
    model = Contact
    template_name = 'test_app/delete_contact.html'
    success_url = reverse_lazy('test_app:history')

    def get_success_url(self):
        return reverse('test_app:history', kwargs={'page': '1'})

    def get(self, request, *args, **kwargs):
        visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        contact = Contact.objects.get(id=self.kwargs['pk'])
        print('DeleteView/getメソッド')
        print(contact)
        print(contact.id)
        print(visitor)
        print(visitor.id)
        print(visitor.is_contacted)
        contact = Contact.objects.get(pk=self.kwargs['pk'])
        context = {
            'contact': contact,
        }
        return render(request, 'test_app/delete_contact.html', context)

    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        # visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        # print(visitor)
        # print(visitor.id)
        # print(visitor.is_contacted)
        # visitor.is_contacted = False
        # print(visitor.is_contacted)
        # visitor.save()
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

    def post(self, request, *args, **kwargs):
        visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        print(visitor)
        print(visitor.id)
        print(visitor.is_contacted)
        visitor.is_contacted = False
        print(visitor.is_contacted)
        visitor.save()
        return self.delete(request)


class VisitorsDelete(DeleteView):

    model = Visitors
    template_name = 'test_app/delete_contact_all.html'
    success_url = reverse_lazy('test_app:history')

    def get_success_url(self):
        return reverse('test_app:history', kwargs={'page': '1'})
    
    def delete(self, request, *args, **kwargs):
        result = super().delete(request, *args, **kwargs)
        # visitor = Visitors.objects.get(contact = self.kwargs['pk'])
        # print(visitor)
        # print(visitor.id)
        # print(visitor.is_contacted)
        # visitor.is_contacted = False
        # print(visitor.is_contacted)
        # visitor.save()
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result

    def form_valid(self, form):
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return super().form_valid(form)

test_app/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  {% comment %} history.htmlにおいて、テーブルの行選択の中にプルダウン設置有効化のために以下配置 {% endcomment %}
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  {% comment %} 来訪者カード等において、日付・時刻の入力フォームのデザインをNarito先生の教えを反映させるため下記配置 {% endcomment %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
      {% comment %} 日付の日本語表記の為配置 {% endcomment %}
  <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script>
      {% comment %} 時刻のウィジェット適用の為以下配置 {% endcomment %}
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/timedropper/1.0/timedropper.min.js"></script>
  {% comment %} datepicker元サイトから借用 {% endcomment %}
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>
  
  {% block head %}{% endblock %}  
  <title>{% block title%}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'test_app:history' page=1 %}">訪問者管理システム</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="navbar-right">
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'test_app:history' page=1 %}">コンタクト一覧</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'test_app:welcome' %}">来訪者カード</a>
      </li>
    </ul>
    </div>

    <div class="collapse navbar-collapse justify-content-end">
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">統計</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="#">管理</a>
      </li>
      <li class="nav-item">
        <a class="nav-link">　</a>
      </li>
    </ul>
    </div>

  </div>
</nav>
  <div class="container-fluid-list">
    <div class="row">
    {% block header %}
    {% endblock %}
    </div>
  </div>

{% block content %}
{% endblock %}
</body>
</html>

test_app/templates/memo.html
         
          {% load widget_tweaks %}
          {% for field in formset %}
            <div class="col" style="padding: 0; padding-left: 12px;">
                 <div class="input-group">
                   <div class="input-group-prepend">
                     <div class="theme-label-contact-edit form-control" for="id_contact-0-interviewer">担当者</div>
                   </div>
                   {% render_field  field.interviewer  class="form-control" style="width: 6rem;" %}
                   {{ formset.0.interviewer }}
                 </div>
             </div>
             <div class="col" style="padding: 0; padding-right: 12px;">
                 <div class="input-group">
                     <div class="input-group-prepend">
                     <div class="theme-label-time-contact-edit form-control" for="id_contact-0-time">退室時刻</div>
                     </div>
                     {% render_field  field.time  class="form-control" %}
                     {{ formset.0.time }}
                 </div>
             </div>
             <div class="input-group">
                 <div class="input-group-prepend">
                 <div class="theme-label-textarea-contact-edit form-control" rows="5" for="id_contact-0-contents">内容</div>
                 </div>
                 {% render_field  field.contents  class="form-control" %}
                 {{ formset.0.contents }}
             </div>
          {% endfor %}